window.VSP_CONTENT = {
  ui: {
    ru: {
      navAbout:'О нас', navArticles:'Статьи', navInterviews:'Интервью',
      heroKicker:'медиа об архитектонике креативных индустрий',
      heroLead:'Проект-исследование и медиа о том, как устроены креативные индустрии — через живые интервью с людьми, которые создают культурную, интеллектуальную и коммерческую ценность.',
      scrollDown:'ЛИСТАЙ ВНИЗ',
      conceptKicker:'что это',
      conceptTitleA:'Мы делаем видимым', conceptTitleB:'реальный опыт',
      conceptBody:'«Вспышка» показывает, как креативные индустрии устроены изнутри. Мы разбираем профессии, процессы и роли через честный разговор — не шаблонные истории успеха, а живой опыт тех, кто делает.',
      missionKicker:'миссия',
      missionA:'Создать независимое пространство, где человек чувствует себя ', missionEm:'свободным и значимым', missionB:' — и обретает право быть собой.',
      visionKicker:'видение',
      visionText:'Собрать медиа, которому доверяют как исследованию и читают как вдохновляющий, интеллектуальный и эстетичный журнал.',
      benefitKicker:'выгода',
      benefitText:'Понимание индустрии через живой опыт без шаблонных историй успеха. Мы берём интервью у тех, кто «варится» в индустриях ежедневно.',
      valuesKicker:'ценности', valuesTitle:'Во что мы верим',
      featuredKicker:'Первое интервью',
      featuredTitle:'Гастрономия как способ сторителлинга',
      featuredDesc:'Алексей Клименко — бренд-шеф и сооснователь гастроагентства Référence à la vie. О том, как рождаются проекты, почему люди важнее бизнес-планов и что такое настоящий «референс жизни».',
      readInterview:'ЧИТАТЬ ИНТЕРВЬЮ →',
      creatorKicker:'автор проекта', creatorName:'Аревик Емишян',
      creatorBio:'Студентка профиля «Ивент-дизайн и экономика впечатлений» Института развития креативных индустрий НИУ ВШЭ. «Вспышка» исследует профессию через интервью с теми, кто создаёт культурную, интеллектуальную и коммерческую ценность.',
      articlesKicker:'статьи', articlesTitle:'Читать медленно',
      backArticles:'← ВСЕ СТАТЬИ', backInterviews:'← ВСЕ ИНТЕРВЬЮ',
      interviewsKicker:'интервью', interviewsTitle:'Голоса индустрии',
      interviewsLead:'Разговоры с теми, кто создаёт креативные индустрии. Читатель видит вокруг себя равных.',
      soon:'Скоро здесь появятся новые интервью.',
      heroBlog:'Блог героя', topQuotes:'топ цитат',
      likedTitle:'Понравилось интервью?', likedText:'Обсуждаем материал у нас в Telegram — заходите.',
      ourTgLabel:'Наш Telegram',
      expandExpand:'РАЗВЕРНУТЬ ИНТЕРВЬЮ ЦЕЛИКОМ', expandCollapse:'СВЕРНУТЬ ИНТЕРВЬЮ',
      footerSections:'РАЗДЕЛЫ', footerFollow:'СЛЕДИТЬ', footerHome:'Главная',
      footerCopy:'© 2026 Вспышка · ИРКИ НИУ ВШЭ', footerMade:'Сделано с любовью к людям',
      phArevik:'Фото Аревик', phCover:'Обложка статьи', phArticle:'Фотография к статье',
      phHero:'Фото героя', phHeroBig:'Фотография героя', phProject:'Фото с проекта',
    },
    en: {
      navAbout:'About', navArticles:'Articles', navInterviews:'Interviews',
      heroKicker:'a media outlet on the architectonics of the creative industries',
      heroLead:'A research project and media outlet about how the creative industries work — through candid interviews with people who create cultural, intellectual and commercial value.',
      scrollDown:'SCROLL DOWN',
      conceptKicker:'what it is',
      conceptTitleA:'We make real experience', conceptTitleB:'visible',
      conceptBody:'Vspyshka shows how the creative industries are built from the inside. We unpack professions, processes and roles through an honest conversation — not template success stories, but the living experience of those who do the work.',
      missionKicker:'mission',
      missionA:'To create an independent space where a person feels ', missionEm:'free and significant', missionB:' — and gains the right to be themselves.',
      visionKicker:'vision',
      visionText:'To build media that is trusted like research and read like an inspiring, intelligent and beautiful magazine.',
      benefitKicker:'benefit',
      benefitText:'Understanding the industry through living experience, without template success stories. We interview those who are immersed in the industries every day.',
      valuesKicker:'values', valuesTitle:'What we believe in',
      featuredKicker:'First interview',
      featuredTitle:'Gastronomy as a way of storytelling',
      featuredDesc:'Alexey Klimenko — brand chef and co-founder of the gastro agency Référence à la vie. On how projects are born, why people matter more than business plans, and what a true “reference of life” is.',
      readInterview:'READ INTERVIEW →',
      creatorKicker:'project author', creatorName:'Arevik Yemishyan',
      creatorBio:'A student of the “Event Design and the Experience Economy” track at the Institute for Creative Industries Development, HSE University. Vspyshka explores the profession through interviews with those who create cultural, intellectual and commercial value.',
      articlesKicker:'articles', articlesTitle:'Read slowly',
      backArticles:'← ALL ARTICLES', backInterviews:'← ALL INTERVIEWS',
      interviewsKicker:'interviews', interviewsTitle:'Voices of the industry',
      interviewsLead:'Conversations with those who create the creative industries. The reader sees equals all around.',
      soon:'New interviews are coming soon.',
      heroBlog:'Guest’s blog', topQuotes:'top quotes',
      likedTitle:'Enjoyed the interview?', likedText:'We discuss the material in our Telegram — come join us.',
      ourTgLabel:'Our Telegram',
      expandExpand:'EXPAND THE FULL INTERVIEW', expandCollapse:'COLLAPSE INTERVIEW',
      footerSections:'SECTIONS', footerFollow:'FOLLOW', footerHome:'Home',
      footerCopy:'© 2026 Vspyshka · HSE ICI', footerMade:'Made with love for people',
      phArevik:'Arevik’s photo', phCover:'Article cover', phArticle:'Article photo',
      phHero:'Guest’s photo', phHeroBig:'Guest’s photo', phProject:'Project photo',
    }
  },

  values: {
    ru: [
      {n:'01', t:'Герой как носитель системы', d:'Каждый герой — это целая система взглядов, решений и привычек. Мы показываем её целиком.'},
      {n:'02', t:'Уважение к опыту', d:'Любой путь ценен. Мы слушаем, не оценивая, и бережно относимся к чужой истории.'},
      {n:'03', t:'Процесс важнее результата', d:'Нам интересно, как рождается решение, а не только то, что получилось в конце.'},
      {n:'04', t:'Ориентир в профессиях', d:'Помогаем аудитории разбираться в профессиях, процессах и ролях креативных индустрий.'},
      {n:'05', t:'Интервью + исследование + медиа', d:'Соединяем живой разговор, аналитику и эстетику журнала в одном формате.'},
      {n:'06', t:'Читатель видит равных', d:'Ты видишь вокруг себя таких же людей — со своими сомнениями и находками.'},
      {n:'07', t:'Независимое пространство', d:'Говорим о профессии честно и свободно — ни от кого не завися.'},
      {n:'08', t:'Свобода быть собой', d:'Помогаем человеку почувствовать себя свободным, значимым и настоящим.'},
      {n:'09', t:'«Я — такой же»', d:'Результат чтения — спокойствие и уверенность: мне нет смысла загоняться.'},
    ],
    en: [
      {n:'01', t:'The hero as a bearer of a system', d:'Every guest is a whole system of views, decisions and habits. We show it in full.'},
      {n:'02', t:'Respect for experience', d:'Every path matters. We listen without judging and treat someone’s story with care.'},
      {n:'03', t:'Process over result', d:'We care how a decision is born, not only what came out in the end.'},
      {n:'04', t:'A guide to professions', d:'We help the audience make sense of the professions, processes and roles of the creative industries.'},
      {n:'05', t:'Interview + research + media', d:'We combine a live conversation, analysis and the aesthetics of a magazine in one format.'},
      {n:'06', t:'The reader sees equals', d:'You see people just like you around — with their own doubts and discoveries.'},
      {n:'07', t:'An independent space', d:'We talk about the profession honestly and freely — dependent on no one.'},
      {n:'08', t:'Freedom to be yourself', d:'We help a person feel free, significant and real.'},
      {n:'09', t:'“I’m just like them”', d:'The result of reading is calm and confidence: there’s no point in stressing out.'},
    ]
  },

  articles: {
    ru: [
      {id:'a1', slot:'art-a1', src:'assets/ph-tishina.jpg', tag:'РЕФЛЕКСИЯ', title:'Тишина как новый ресурс креативных индустрий',
        excerpt:'Почему пауза становится ценнее нового контента и как это меняет работу тех, кто создаёт впечатления.',
        pull:'Смысл рождается там, где мы перестаём торопиться.',
        // body:[
        //   'Креативные индустрии долго измеряли себя скоростью: чем больше выпущено, тем заметнее результат. Но у бесконечного потока есть предел — внимание. Когда его не хватает, выигрывает не тот, кто громче, а тот, кто точнее.',
        //   'Тишина здесь — не про отсутствие действия, а про качество внимания. Это способность остановиться, услышать контекст и задать вопрос, который действительно важен. Именно из таких пауз чаще всего вырастают сильные проекты.',
        //   'Мы всё чаще видим, как команды сознательно замедляются: сокращают количество релизов, возвращаются к исследованию аудитории, дают идее вызреть. Это не роскошь, а рабочая стратегия — и, кажется, новая норма.',
        // ]
      },
      {id:'a2', slot:'art-a2', src:'assets/ph-result.png', tag:'ПРОЦЕСС', title:'Как читать процесс: почему важнее «как», а не «что»',
        excerpt:'Разбираем, что скрывается за готовым результатом и почему процесс — самое интересное в любой профессии.',
        pull:'Результат — это верхушка. Настоящая история — в решениях по пути.',
        // body:[
        //   'Готовый проект всегда выглядит цельным и неизбежным. Но за ним стоят десятки развилок, где всё могло сложиться иначе. Эти развилки и есть профессия.',
        //   'Когда мы спрашиваем «как ты это сделал», человек начинает рассказывать о сомнениях, ограничениях и случайностях. Именно там видно мышление — а не в финальной картинке.',
        //   'Поэтому «Вспышка» смотрит на процесс. Он честнее результата и полезнее для того, кто только ищет свой путь в индустрии.',
        // ]
      },
      {id:'a3', slot:'art-a3', src:'assets/ph-city.png', tag:'ГОРОД', title:'Города как сцена: событие вместо контента',
        excerpt:'Как креативные форматы превращают пространство в опыт, который остаётся с человеком надолго.',
        pull:'Мы запоминаем не то, что увидели, а то, что прожили.',
        // body:[
        //   'Город всё чаще становится площадкой для впечатлений: поп-апы, маршруты, гастрономические сеты, временные пространства. Всё это — язык, на котором индустрии говорят с человеком.',
        //   'Такое событие не потребляют, как ленту. В нём участвуют. И именно участие превращает разовый визит в личную историю, о которой хочется рассказать.',
        //   'Для авторов это вызов: спроектировать не картинку, а переживание. Но именно здесь и рождается настоящая ценность.',
        // ]
      },
    ],
    en: [
      {id:'a1', slot:'art-a1', src:'assets/ph-tishina.jpg', tag:'REFLECTION', title:'Silence as a new resource of the creative industries',
        excerpt:'Why a pause becomes more valuable than new content and how it changes the work of those who create impressions.',
        pull:'Meaning is born where we stop rushing.',
        // body:[
        //   'The creative industries long measured themselves by speed: the more you release, the more visible the result. But the endless stream has a limit — attention. When there isn’t enough of it, the winner isn’t the loudest but the most precise.',
        //   'Silence here isn’t about the absence of action, but about the quality of attention. It’s the ability to stop, hear the context and ask a question that truly matters. Strong projects most often grow out of such pauses.',
        //   'We increasingly see teams deliberately slowing down: cutting the number of releases, returning to audience research, letting an idea mature. It’s not a luxury but a working strategy — and, it seems, the new norm.',
        // ]
      },
      {id:'a2', slot:'art-a2', src:'assets/ph-result.png', tag:'PROCESS', title:'How to read process: why “how” matters more than “what”',
        excerpt:'We unpack what hides behind the finished result and why process is the most interesting thing in any profession.',
        pull:'The result is the tip. The real story is in the decisions along the way.',
        // body:[
        //   'A finished project always looks whole and inevitable. But behind it stand dozens of forks where everything could have turned out differently. Those forks are the profession itself.',
        //   'When we ask “how did you do this”, a person starts talking about doubts, constraints and accidents. That’s where thinking shows — not in the final picture.',
        //   'That’s why Vspyshka looks at the process. It’s more honest than the result and more useful for someone just looking for their path in the industry.',
        // ]
      },
      {id:'a3', slot:'art-a3', src:'assets/ph-city.png', tag:'CITY', title:'Cities as a stage: an event instead of content',
        excerpt:'How creative formats turn space into an experience that stays with a person for a long time.',
        pull:'We remember not what we saw, but what we lived through.',
        // body:[
        //   'The city increasingly becomes a venue for impressions: pop-ups, routes, gastronomic sets, temporary spaces. All of it is a language the industries use to speak with a person.',
        //   'Such an event isn’t consumed like a feed. You take part in it. And it’s participation that turns a one-off visit into a personal story you want to tell.',
        //   'For creators it’s a challenge: to design not a picture but an experience. But that’s exactly where real value is born.',
        // ]
      },
    ]
  },

  interviews: {
    ru: {
      klimenko: {
        id:'klimenko', slot:'iv-klimenko', src:'assets/ph-chef.jpg', tag:'ГАСТРОНОМИЯ', date:'26 июня 2026',
        title:'Гастрономия как способ сторителлинга',
        name:'Алексей Клименко',
        role:'бренд-шеф, сооснователь гастроагентства Référence à la vie',
        hero:'О том, как рождаются гастрономические проекты, почему люди важнее бизнес-планов и что такое настоящий «референс жизни».',
        heroTg:'https://t.me/referencealavie',
        intro:[
          'Гастрономия сегодня всё чаще выходит за рамки ресторанного бизнеса и становится частью культурных индустрий. Через еду можно рассказывать истории, знакомить с традициями и создавать сообщества.',
          'Алексей Клименко вместе с партнёром Константином Ердаковым развивает гастропроекты, организует путешествия и поп-ап-рестораны. В интервью — о том, как рождаются концепции и почему главное в проекте всегда люди.',
        ],
        quotes:[
          'В первую очередь — люди, которые в нём счастливы. Вот это настоящий успех.',
          'Такие проекты я ассоциирую с нанизыванием бусинок на нитку с иголкой.',
          'Да просто человеком, который любит жизнь!',
        ],
        qa:[
          {q:'— Расскажи, как пришёл к тому, чем занимаешься сейчас?', a:'— Да запросто! Начал работать поваром в 15 лет. Из Магнитогорска перебрался в Питер — там работал с крутыми шефами. Потом переехал в Москву и сам стал шефом. В итоге вырос до бренд-шефа в сети из 11 ресторанов. Сейчас я в свободном плавании: развиваю своё гастрокультурное направление, устраиваю поп-апы и гастрономические туры.'},
          {q:'— Ты работаешь с партнёром Костей. Что у вас за химия такая?', a:'— У нас с Костей прям «супермэтч»: всё, что делаем, рождается из огромной любви — ради людей и для людей. Конечно, выйти в плюс — это круто, но главное, чтобы самому было классно. Тогда и другие будут счастливы.'},
          {q:'— А как вообще родилась идея «Kofta&Boza»?', note:'Kofta&Boza — поп-ап турецкого фастфуда, созданный Алексеем и Костей в рамках агентства Référence à la vie.', a:'— О, это прикольная история. Полтора года назад я придумал одно блюдо. Тогда мы с Костей ещё не так плотно общались, но он такой: «Давай займёмся брендингом!» — и сделал его. Потом мы начали искать инвесторов — без всякого бизнес-плана, просто ходили и каждому предлагали: «Хотите — можем сделать». Сначала открыли небольшой бар, а потом заполнили всё пространство. Во второй раз гости шли нескончаемым потоком — с 10 утра до полуночи. Видеть такой отклик — это просто кайф!'},
          {q:'— То есть проект рос постепенно, шаг за шагом?', a:'— Точно! Я такие проекты ассоциирую с нанизыванием бусинок на нитку с иголкой. Сначала есть просто блюдо, потом появляется название, а к нему потихоньку присоединяются другие детали.'},
          {q:'— Что ты имеешь в виду под «референсом жизни»?', note:'Référence à la vie — название гастроагентства, переводится как «референс жизни».', a:'— «Референс жизни» — это наша главная идея. Мы хотим показывать и рассказывать, как можно жить по-другому, немного переносить людей в наш мир, делиться своим взглядом на жизнь.'},
          {q:'— А название как придумали?', a:'— Чисто случайно! Представь: делаешь что-то реально классное — например, офигенный завтрак. Вот это и есть «референс жизни». Мы просто сидели, болтали — и вдруг название само всплыло. Взяли слово из обычной жизни, и оно идеально подошло!'},
          {q:'— А почему на французском? У тебя особая любовь к Франции?', a:'— Да просто звучит красиво! Плюс во французской кухне я провёл немало времени: куча проектов была связана с ресторанами и французской гастрономией. Да и работа с Давидом Эмерле тоже повлияла.'},
          {q:'— И кем ты себя сейчас считаешь?', a:'— Да просто человеком, который любит жизнь!'},
          {q:'— Кто из профессионалов на тебя больше всего повлиял?', a:'— Очень ценю Бориса Зарькова. Полтора года работал в Luciano — тогда он учился на MBA и постоянно делился с нами знаниями. Опыт из White Rabbit очень помог мне в развитии своих проектов. Ещё нравится Денис Бобков и то, что он делает с Виталиком Бганцовым.'},
          {q:'— Что для тебя самое главное в проекте?', a:'— Главное — передать атмосферу во всём: через еду, дизайн, мелкие детали. Это ключ ко всему.'},
          {q:'— А что для тебя успех проекта?', a:'— В первую очередь — люди, которые в нём счастливы. Вот это настоящий успех.'},
          {q:'— Откуда берёшь вдохновение для новых идей?', a:'— Например, в 2024 году делали проект в школе французского языка. Я как раз посмотрел новый фильм Франсуа Озона — он про Алжир и жизнь французов там. И я такой: «Давай сделаем французско-алжирскую кухню!» Приготовили таджин с улитками: алжирский стиль, но с французскими продуктами. Получилось круто!'},
          {q:'— Получается, вдохновение часто приходит случайно?', a:'— Думаю, дело не в случайности, а в умении жонглировать ситуациями. Они у всех происходят, но важно, как ты ими управляешь.'},
          {q:'— Расскажи про проект в Переделкино.', a:'— Меня туда позвала Дарья Беглова. У команды уже был концепт по десятилетиям, а я подбирал вкусы и разрабатывал блюда. У них всё было готово — и аудиоряд, и оформление пространства. А я отвечал за еду.'},
          {q:'— Как тебе работа с командой Переделкино?', a:'— Супер! У них отличная команда ивентщиков, которые всегда думают о человеке. Проект получился классный, надеюсь, ещё что-нибудь замутим вместе.'},
          {q:'— Где черпаешь вдохновение, когда речь про еду и творчество?', a:'— Только в путешествиях и изучении других культур. Без этого никуда!'},
          {q:'— Так что, по-твоему, залог успешного проекта?', a:'— Какими бы продуманными ни были процессы, без людей ничего не выйдет. Они — главный показатель крутых проектов. Бизнес-план — это уже потом, он просто объясняет, почему тебе стоит дать деньги.'},
          {q:'— Ты говорил про спонтанность. Как она отражается на работе?', a:'— Спонтанность — это какая-то своя мудрость. Бывает, делаешь творческий проект: три дня пашешь, ничего не зарабатываешь… А потом вдруг — бам! — прилетает проект, где зарабатываешь в три раза больше. Вот она, жизнь!'},
        ],
        outro:'Гастрономия в интерпретации Алексея — это больше, чем профессия. Это способ исследовать мир и создавать впечатления, которые остаются с человеком надолго.',
      }
    },
    en: {
      klimenko: {
        id:'klimenko', slot:'iv-klimenko', src:'assets/ph-chef.jpg', tag:'GASTRONOMY', date:'June 26, 2026',
        title:'Gastronomy as a way of storytelling',
        name:'Alexey Klimenko',
        role:'brand chef, co-founder of the gastro agency Référence à la vie',
        hero:'On how gastronomic projects are born, why people matter more than business plans, and what a true “reference of life” is.',
        heroTg:'#',
        intro:[
          'Today gastronomy increasingly goes beyond the restaurant business and becomes part of the cultural industries. Through food you can tell stories, introduce traditions and build communities.',
          'Alexey Klimenko, together with his partner Konstantin Yerdakov, develops gastro projects, organises travel and pop-up restaurants. In this interview — on how concepts are born and why the main thing in a project is always people.',
        ],
        quotes:[
          'First of all — the people who are happy in it. That’s what real success is.',
          'I associate such projects with threading beads onto a string with a needle.',
          'Just a person who loves life!',
        ],
        qa:[
          {q:'— Tell us, how did you come to what you do now?', a:'— Easily! I started working as a cook at 15. From Magnitogorsk I moved to St. Petersburg — worked there with brilliant chefs. Then I moved to Moscow and became a chef myself. Eventually I grew into a brand chef for a chain of 11 restaurants. Now I’m on my own: I develop my gastro-cultural direction, run pop-ups and gastronomic tours.'},
          {q:'— You work with your partner Kostya. What kind of chemistry do you two have?', a:'— Kostya and I are a real “super-match”: everything we do is born from huge love — for people and for the sake of people. Of course, turning a profit is great, but the main thing is that it feels great for me. Then others will be happy too.'},
          {q:'— And how did the idea of “Kofta&Boza” come about at all?', note:'Kofta&Boza — a pop-up of Turkish fast food created by Alexey and Kostya under the Référence à la vie agency.', a:'— Oh, that’s a fun story. A year and a half ago I came up with one dish. Back then Kostya and I didn’t communicate that closely yet, but he was like: “Let’s do the branding!” — and he did it. Then we started looking for investors — with no business plan at all, we just went around offering everyone: “If you want — we can make it.” First we opened a small bar, then we filled the whole space. The second time guests came in an endless stream — from 10 a.m. to midnight. Seeing that response is just a thrill!'},
          {q:'— So the project grew gradually, step by step?', a:'— Exactly! I associate such projects with threading beads onto a string with a needle. First there’s just a dish, then a name appears, and other details slowly join it.'},
          {q:'— What do you mean by a “reference of life”?', note:'Référence à la vie — the name of the gastro agency, which translates as “reference of life”.', a:'— A “reference of life” is our main idea. We want to show and tell how you can live differently, to move people a little into our world, to share our view of life.'},
          {q:'— And how did you come up with the name?', a:'— Purely by chance! Imagine: you make something really cool — an awesome breakfast, say. That’s a “reference of life”. We were just sitting, chatting — and suddenly the name popped up on its own. We took a word from everyday life, and it fit perfectly!'},
          {q:'— And why in French? Do you have a special love for France?', a:'— It just sounds beautiful! Plus I spent a lot of time with French cuisine: tons of projects were tied to restaurants and French gastronomy. And working with David Emerlé influenced me too.'},
          {q:'— And who do you consider yourself to be now?', a:'— Just a person who loves life!'},
          {q:'— Which professionals influenced you the most?', a:'— I really value Boris Zarkov. I worked at Luciano for a year and a half — back then he was studying for an MBA and constantly shared his knowledge with us. The experience from White Rabbit helped me a lot in developing my own projects. I also like Denis Bobkov and what he does with Vitaly Bgantsov.'},
          {q:'— What’s the most important thing in a project for you?', a:'— The main thing is to convey the atmosphere in everything: through the food, the design, the small details. That’s the key to it all.'},
          {q:'— And what is a project’s success for you?', a:'— First of all — the people who are happy in it. That’s what real success is.'},
          {q:'— Where do you draw inspiration for new ideas?', a:'— For example, in 2024 we did a project at a French language school. I had just watched François Ozon’s new film — it’s about Algeria and the life of the French there. And I was like: “Let’s make Franco-Algerian cuisine!” We cooked a tagine with snails: Algerian style, but with French products. It turned out great!'},
          {q:'— So inspiration often comes by chance?', a:'— I think it’s not about chance, but about the ability to juggle situations. They happen to everyone, but what matters is how you manage them.'},
          {q:'— Tell us about the project in Peredelkino.', a:'— Daria Beglova invited me there. The team already had a concept built around decades, and I picked the flavours and developed the dishes. They had everything ready — the soundscape and the space design. And I was responsible for the food.'},
          {q:'— How was working with the Peredelkino team?', a:'— Super! They have a great team of event people who always think about the person. The project turned out cool, I hope we’ll cook up something together again.'},
          {q:'— Where do you find inspiration when it comes to food and creativity?', a:'— Only in travel and in studying other cultures. There’s no way without it!'},
          {q:'— So what, in your view, is the key to a successful project?', a:'— No matter how well thought-out the processes are, nothing works without people. They are the main indicator of cool projects. The business plan comes later, it just explains why you’re worth giving money to.'},
          {q:'— You mentioned spontaneity. How does it show up in your work?', a:'— Spontaneity is a kind of wisdom of its own. Sometimes you do a creative project: you grind for three days, earn nothing… And then suddenly — bam! — a project lands where you earn three times more. That’s life for you!'},
        ],
        outro:'Gastronomy as Alexey interprets it is more than a profession. It’s a way to explore the world and create impressions that stay with a person for a long time.',
      }
    }
  }
};
